### ISSUE TITLE
Participant exceptions

### ISSUE THREAD

**Issue by sammacbeth** [Presage/Presage2#28]
Imported from lighthouse. Original ticket at: http://sammacbeth.lighthouseapp.com/projects/65108/tickets/2. Created by sammacbeth (at gmail) - 2010-11-30 19:29:09 UTC

Calls to participant functions should have specific exceptions for error handling.

**Comment by brendanneville** [comment]
Cheers!

Hey Sam,

Is Jeremy around today? I've been trying to contact him to no avail and its
rather important I do so today.

Cheers,

Brendan
