### ISSUE TITLE
Wrapper for scenario generation

### ISSUE THREAD

**Issue by sammacbeth** [Presage/Presage2#34]
RunnableSimulation - wrapper for procedural scenario generation to allow Simulators to be generated from them.

This will allow parameterised scenarios to be created and run by some controller automatically.

**Comment by sammacbeth** [comment]
Added by https://github.com/Presage/Presage2/commit/220f643b15fb9c8df2424779dfd3a1b4c8cddd44

**Comment by javajawa** [comment]
Did you know: if you include:
Closes #&lt;issue>
in the commit message, GitHub will add this for you :)

**Comment by sammacbeth** [comment]
Yes, but I forgot and couldn't be arsed to rebase...
