### ISSUE TITLE
Implement edge behaviour for physical environments

### ISSUE THREAD

**Issue by davekyle** [Presage/Presage2#41]
When an agent reaches the edge of an environment, different behaviours should be able to be specified (either by an enum, or by allowing the user to extend a class defining what happens).
- Each edge of an environment should be able to be set differently.
- Possible behaviours (either if you're choosing enums, or as ones to do as examples/builtins):
  - **Stop** Agent just stops
  - **Bounce** Agent reflects off in some way
  - **Except** Environment throws an exception
  - **Wrap** Agent appears on the matching opposite side of the environment
- I can't help but think of all the problems that will occur if you don't have rectangular environments, or ones with a standard cartesian coordinate system, but I guess we can leave that for later :P

**Comment by sammacbeth** [comment]
What about if an agent goes over two edges at once? Is there some precedence defined or do we just do both? Depending on the behaviours this could have different results depending which order they are executed, leading to unpredictable results.
