### ISSUE TITLE
Conversation protocols

### ISSUE THREAD

**Issue by davekyle** [Presage/Presage2#43]
Need to be able to specify protocols for conversations
- Custom conversation protocols should be definable, but the obvious ones are:
  - "Handshake"-style conversation where there are only two agents that exchange some information
  - Voting - where multiple agents vote, possibly in more than one round.

**Comment by sammacbeth** [comment]
Did you mention a paper relating to this which could be useful?

**Comment by davekyle** [comment]
Only if you feel like coming up with the protocol for implementing Paxos, but that's kind of what I'm going to be doing next week and writing a paper on :P

The paper was for the agent architecture that does internal-simulation. Will email you it.

**Comment by davekyle** [comment]
Basically what I'm looking for is just some framework inside which to write the actual protocol myself... Simple example would be nice, á la HelloWorld.
