### ISSUE TITLE
POM Dependency Issues

### ISSUE THREAD

**Issue by javajawa** [Presage/Presage2#48]
ee-sm1106.ee.ic.ac.uk is a restricted access machine; Maven attempts to obtain a number of the dependencies from this machine.

**Comment by sammacbeth** [comment]
You should be able to access the machine on the college network via the VPN. I'm hoping to resolve this issue at some point by moving the maven repo to a machine which is not behind the college firewall.

**Comment by javajawa** [comment]
I figured that would probably be the case; I'm working my way through the command line VPN documentation currently.

I can always install a GDE if it comes to it :P

**Comment by badralfaiya** [comment]
Can i replace http://ee-sm1106.ee.ic.ac.uk:8080/nexus/content/groups/public/  OR http://dev.presage2.info/nexus/content/groups/public/ 
with something new e.g. http://github.com/Presage/Presage2/xxxxxx? 
Thanks
