### ISSUE TITLE
Presage2 Website - 403 on Sign-in / Sign-up

### ISSUE THREAD

**Issue by javajawa** [Presage/Presage2#58]
I appear to be getting consistent 403 Forbidden errors when attempting to sign up  for the forum. This also occurs when trying to sign in with one of my elsewhere accounts.

```
Forbidden (403)
CSRF verification failed. Request aborted.

More information is available with DEBUG=True.
```

**Comment by sammacbeth** [comment]
What authentication provider are you using? I didn't get any issues with google account login.

**Comment by javajawa** [comment]
Issue turned out to be, as it occasionally is, cookie settings (which they broke some more in Chrome 19).

Though, 403 is a slightly odd error for a missing cookie...
