### ISSUE TITLE
Is http://dev.presage2.info/nexus/content/groups/public/  down? 

### ISSUE THREAD

**Issue by badralfaiya** [Presage/Presage2#69]
I am trying to use Presage2 for my PhD research, but it doesnt seem to work because http://www.presage2.info/ is down. Thanks.

**Comment by sammacbeth** [comment]
It seems the domain registration expired. I have set up of mirror of the nexus repository though, so you can still get the builds. Just change the repository in your `pom.xml` from `http://dev.presage2.info/nexus/content/repositories/releases` to `http://dev.presage2.sammacbeth.eu/nexus/content/repositories/releases` and it should all work properly.
